### ISSUE TITLE
Disable Mod Tooltip in JEI

### ISSUE THREAD

**Issue by phit** [AllTheMods/ATM-6#160]
**Is your feature request related to a problem? Please describe.**

Items have their owning mod twice in their tooltip in JEI. Once from JEI and from the mod "Mod Name Tooltip"

**Describe the solution you'd like**

edit `config/jei-client.toml` and empty `ModNameFormat`

```toml
[modname]
	#Formatting for mod name tooltip
	#Use these formatting keys:
	#black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
	#obfuscated, bold, strikethrough, underline, italic
	ModNameFormat = ""

```
